---
version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@11.1
  shellcheck: circleci/shellcheck@3.1
  molecule: mtpettyp/molecule@2.0.0

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - molecule/test:
          role_name: buluma.proxychains
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
      - shellcheck/check:
          exclude: SC2196
          filters: *filters