---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    dynamic_chain: true
    chain_len: 2
    tcp_read_time_out: 16000
    tcp_connect_time_out: 10000

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
  tasks:
    - name: "Include buluma.python_pip"
      ansible.builtin.include_role:
        name: "buluma.python_pip"
    - name: "Include buluma.epel"
      ansible.builtin.include_role:
        name: "buluma.epel"
    - name: "Include buluma.pip"
      ansible.builtin.include_role:
        name: "buluma.pip"
    - name: "Include buluma.proxychains"
      ansible.builtin.include_role:
        name: "buluma.proxychains"
