---
- name: Verify
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Check proxychains config exists.
      ansible.builtin.command:
        cmd: cat /etc/proxychains.conf
      changed_when: false
      register: proxychains_conf

    - name: Show proxychains config.
      ansible.builtin.debug:
        var: proxychains_conf.stdout_lines
      tags: molecule-notest

    - name: Check proxychains binary is present.
      ansible.builtin.command:
        cmd: which proxychains
      changed_when: false
