---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Check proxychains config.
    command: |
      cat /etc/proxychains.conf
    register: proxychains_conf

  - name: Finding some webservers through proxy.
    command: |
      proxychains nmap 127.0.0.1
    register: nmap_test
